{
    "type": "end",
    "timestamp": "2024-02-10T19:38:01.868554",
    "step_id": "Guessing_Game.main.game_loop",
    "task_id": "Guessing_Game.main",
    "result": null,
    "exception": {
        "type": "builtins.EOFError",
        "args": [],
        "details": "Traceback (most recent call last):\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\src\\quest\\historian.py\", line 602, in handle_step\n    result = await result\n             ^^^^^^^^^^^^\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\numGuess.py\", line 41, in game_loop\n    while((res := await play_game()) != -1):\n                  ^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\src\\quest\\wrappers.py\", line 15, in new_func\n    return await find_historian().handle_step(func.__name__, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\src\\quest\\historian.py\", line 602, in handle_step\n    result = await result\n             ^^^^^^^^^^^^\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\numGuess.py\", line 31, in play_game\n    guess = await getGuess()\n            ^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\src\\quest\\wrappers.py\", line 15, in new_func\n    return await find_historian().handle_step(func.__name__, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\src\\quest\\historian.py\", line 602, in handle_step\n    result = await result\n             ^^^^^^^^^^^^\n  File \"c:\\Users\\User\\Documents\\2024-1 Winter BYU\\CS301R\\numGuess.py\", line 15, in getGuess\n    guess = input()\n            ^^^^^^^\nEOFError\n"
    }
}